### ISSUE TITLE
Initial Package Structure

### ISSUE THREAD

**Issue by tisto** [kitconcept/kitconcept.blog#1]
# ToDo

* [x] create initial package structure with cookie-cutter https://github.com/collective/cookiecutter-plone-starter (alternative https://github.com/kitconcept/cookiecutter-plone)
* [ ] create a "blog post" content type (folderish, blocks enabled)
  * [x] title
  * [x] description
  * [x] preview_image behavior
  * [ ] authors (multi-reference field)
* [ ] create an "blog author" content type
  * [x] name
  * [x] description
  * [ ] image
* [ ] create a blog author view
  * [ ] name
  * [ ] description
  * [ ] image
  * [ ] list of all blog posts (chronologically)
* [ ] create a blog authors listing -> not necessary for now
* [ ] create a blogs view -> not necessary for now
* [ ] create example content profile
  * [ ] front page lists all blog posts
  * [ ] four blog post examples
  * [ ] three blog authors examples (multiple authors per blog post, author with multiple blog posts)

**Comment by jnptk** [comment]
@tisto as this is now [collective.blog](https://github.com/collective/collective.blog) shall we archive this repo?

**Comment by tisto** [comment]
@jnptk yes.
